--- Utility used: db2look -d <DataBase> -e -t <Table>
------------------------------------------------
-- DDL Statements for Table "CUSTOMERS"
------------------------------------------------
CREATE TABLE "CUSTOMERS"  (
"ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
START WITH +1
INCREMENT BY +1
MINVALUE +1
MAXVALUE +9223372036854775807
NO CYCLE
CACHE 20
NO ORDER ) ,
"DELETED" INTEGER NOT NULL WITH DEFAULT 0 ,
"ADDRESS" VARCHAR(255 OCTETS) ,
"BONUS" INTEGER ,
"CREATED" TIMESTAMP ,
"LASTNAME" VARCHAR(255 OCTETS) ,
"NAME" VARCHAR(255 OCTETS) ,
"PHONENUMBER" VARCHAR(255 OCTETS) ,
"UPDATED" TIMESTAMP )
IN "USERSPACE1"
ORGANIZE BY ROW;

-- DDL Statements for Primary Key on Table "CUSTOMERS"

ALTER TABLE "CUSTOMERS" ADD PRIMARY KEY ("ID");

-- DDL Statements for Indexes on Table "CUSTOMERS"

SET NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "UKIV88MD1XFWKBHN2MD2VY02PNB" ON "CUSTOMERS" ("NAME" ASC, "LASTNAME" ASC) 
COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "TYPEFILMS"
------------------------------------------------

CREATE TABLE "TYPEFILMS"  (
                  "ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                    START WITH +1
                    INCREMENT BY +1
                    MINVALUE +1
                    MAXVALUE +9223372036854775807
                    NO CYCLE
                    CACHE 20
                    NO ORDER ) ,
                  "DELETED" INTEGER NOT NULL WITH DEFAULT 0 ,
                  "DAYSTORETURN" INTEGER ,
                  "NAME" VARCHAR(255 OCTETS) ,
                  "PRICE" DOUBLE )
                 IN "USERSPACE1"
                 ORGANIZE BY ROW;


-- DDL Statements for Primary Key on Table "TYPEFILMS"
ALTER TABLE "TYPEFILMS" ADD PRIMARY KEY ("ID");



-- DDL Statements for Indexes on Table "TYPEFILMS"

SET NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "UK_PHG0P3XEPEWY2L2VG8UXRJU2" ON "TYPEFILMS" ("NAME" ASC)
COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "FILMS"
------------------------------------------------


CREATE TABLE "FILMS"  (
                  "ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                    START WITH +1
                    INCREMENT BY +1
                    MINVALUE +1
                    MAXVALUE +9223372036854775807
                    NO CYCLE
                    CACHE 20
                    NO ORDER ) ,
                  "DELETED" INTEGER NOT NULL WITH DEFAULT 0 ,
                  "CREATED" TIMESTAMP ,
                  "INVENTORYRENT" INTEGER ,
                  "INVENTORYSTORE" INTEGER ,
                  "TITLE" VARCHAR(255 OCTETS) ,
                  "UPDATED" TIMESTAMP ,
                  "TYPE_ID" BIGINT )
                 IN "USERSPACE1"
                 ORGANIZE BY ROW;


-- DDL Statements for Primary Key on Table "FILMS"
ALTER TABLE "FILMS"  ADD PRIMARY KEY("ID");

-- DDL Statements for Indexes on Table "FILMS"

SET NLS_STRING_UNITS = 'SYSTEM';


CREATE UNIQUE INDEX "UK_P58GKMYDWLOXO5SWYV4ADQTBT" ON "FILMS" ("TITLE" ASC)
                COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Foreign Keys on Table "FILMS"

ALTER TABLE "FILMS" ADD CONSTRAINT "FKL1KAHW7VLPDSO6QVERL3HPJMC" FOREIGN KEY
                ("TYPE_ID")  REFERENCES "TYPEFILMS" ("ID")
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
        ENFORCED  ENABLE QUERY OPTIMIZATION;


------------------------------------------------
-- DDL Statements for Table "RENTALS"
------------------------------------------------
CREATE TABLE "RENTALS"  (
                  "ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                    START WITH +1
                    INCREMENT BY +1
                    MINVALUE +1
                    MAXVALUE +9223372036854775807
                    NO CYCLE
                    CACHE 20
                    NO ORDER ) ,
                  "DELETED" INTEGER NOT NULL WITH DEFAULT 0 ,
                  "CODE" VARCHAR(255 OCTETS) ,
                  "CREATED" TIMESTAMP ,
                  "STATUS" VARCHAR(255 OCTETS) ,
                  "CUSTOMER_ID" BIGINT NOT NULL )
                 IN "USERSPACE1"
                 ORGANIZE BY ROW;


-- DDL Statements for Primary Key on Table "RENTALS"
ALTER TABLE "RENTALS"  ADD PRIMARY KEY ("ID");


-- DDL Statements for Indexes on Table "RENTALS"
SET NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "UK_B2WKEXL6C5AC3FVXLBOSV1UMJ" ON "RENTALS"
 ("CODE" ASC) COMPRESS NO INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Foreign Keys on Table "RENTALS"

ALTER TABLE "RENTALS"
        ADD CONSTRAINT "FKCXN0LR4SJTXI7U4NXSHBAJ83U" FOREIGN KEY
                ("CUSTOMER_ID")
        REFERENCES "CUSTOMERS"
                ("ID")
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
        ENFORCED
        ENABLE QUERY OPTIMIZATION;		

------------------------------------------------
-- DDL Statements for Table "PAYMENTS"
------------------------------------------------


CREATE TABLE "PAYMENTS"  (
                  "ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                    START WITH +1
                    INCREMENT BY +1
                    MINVALUE +1
                    MAXVALUE +9223372036854775807
                    NO CYCLE
                    CACHE 20
                    NO ORDER ) ,
                  "DELETED" INTEGER NOT NULL WITH DEFAULT 0 ,
                  "AMOUNT" DECIMAL(19,2) ,
                  "REASONPAYMENT" VARCHAR(255 OCTETS) ,
                  "TYPEPAYMENT" VARCHAR(255 OCTETS) ,
                  "CUSTOMER_ID" BIGINT NOT NULL ,
                  "RENTAL_ID" BIGINT NOT NULL )
                 IN "USERSPACE1"
                 ORGANIZE BY ROW;


-- DDL Statements for Primary Key on Table "PAYMENTS"
ALTER TABLE "PAYMENTS" ADD PRIMARY KEY ("ID");

-- DDL Statements for Foreign Keys on Table "PAYMENTS"

ALTER TABLE "PAYMENTS"
        ADD CONSTRAINT "FK45DP0030S8E3MYD8N6KY4E79G" FOREIGN KEY
                ("CUSTOMER_ID")
        REFERENCES "CUSTOMERS"
                ("ID")
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
        ENFORCED
        ENABLE QUERY OPTIMIZATION;

ALTER TABLE "PAYMENTS"
        ADD CONSTRAINT "FK55TLWG2O3718M5FJUNW4OMEV7" FOREIGN KEY
                ("RENTAL_ID")
        REFERENCES "RENTALS"
                ("ID")
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
        ENFORCED
        ENABLE QUERY OPTIMIZATION;		

------------------------------------------------
-- DDL Statements for Table "RENTAL_FILM"
------------------------------------------------		

CREATE TABLE rental_film (
       id bigint generated by default as identity,
        deleted integer default 0 not null,
        amount integer,
        returnWithoutDue date,
        film_id bigint,
        rental_id bigint,
        primary key (id)
);	

alter table rental_film add constraint FKdbwt9ufyfgw8icwygnqrwb4ra 
       foreign key (film_id) 
       references films;

    
alter table rental_film add constraint FKnn3wdlagotw7gi7nic2n8f2lb 
       foreign key (rental_id) 
       references rentals;
	   
	   
